/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistafravemax.vista;

import javax.swing.JOptionPane;
import proyectoventasg23.AccesoADatos.ProductoData;
import proyectoventasg23.Entidades.Producto;



public class ProductoAdm extends javax.swing.JInternalFrame {


private ProductoData ProData = new ProductoData();
private Producto nuevoPro = null;
    
    /**
     * Creates new form Producto
     */
    public ProductoAdm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jNombre = new javax.swing.JLabel();
        jtNom = new javax.swing.JTextField();
        jDescripcion = new javax.swing.JLabel();
        jtDes = new javax.swing.JTextField();
        jPrecio = new javax.swing.JLabel();
        jtPre = new javax.swing.JTextField();
        jStock = new javax.swing.JLabel();
        jtSto = new javax.swing.JTextField();
        jbGuardar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jTextField3.setText("jTextField3");

        setBorder(null);
        setResizable(true);
        setTitle("Administración de Productos");
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jNombre.setText("Nombre");
        getContentPane().add(jNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 81, -1, -1));
        getContentPane().add(jtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 73, 133, -1));

        jDescripcion.setText("Descripción");
        getContentPane().add(jDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 123, -1, -1));
        getContentPane().add(jtDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 115, 133, -1));

        jPrecio.setText("Precio");
        getContentPane().add(jPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 165, -1, -1));
        getContentPane().add(jtPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 157, 133, -1));

        jStock.setText("Stock");
        getContentPane().add(jStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 207, -1, -1));
        getContentPane().add(jtSto, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 199, 133, -1));

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jbGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 241, -1, -1));

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 241, -1, -1));

        jButton1.setText("Modificar");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 241, -1, -1));

        jButton2.setText("Eliminar");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 241, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // TODO add your handling code here:
           
        String nombre = jtNom.getText();
        String descripcion = jtDes.getText();
        String precio = jtPre.getText();
        String stock = jtSto.getText();
        if(nombre.isEmpty()||descripcion.isEmpty()||precio.isEmpty()|| stock.isEmpty()){
            JOptionPane.showMessageDialog(this,"no puede haber campos vacios");
        
      
      }  
     
    }//GEN-LAST:event_jbGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jDescripcion;
    private javax.swing.JLabel jNombre;
    private javax.swing.JLabel jPrecio;
    private javax.swing.JLabel jStock;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JTextField jtDes;
    private javax.swing.JTextField jtNom;
    private javax.swing.JTextField jtPre;
    private javax.swing.JTextField jtSto;
    // End of variables declaration//GEN-END:variables
}
