/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoventasg23.Vistas;

/**
 *
 * @author Altamirano
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jProducto = new javax.swing.JMenu();
        jAdmiPro = new javax.swing.JMenuItem();
        jConsProdu = new javax.swing.JMenuItem();
        jClientes = new javax.swing.JMenu();
        jAdmiClien = new javax.swing.JMenuItem();
        jConsClien = new javax.swing.JMenuItem();
        jVentas = new javax.swing.JMenu();
        jAdmiVen = new javax.swing.JMenuItem();
        jConsVen = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jProducto.setText("Producto");
        jProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProductoActionPerformed(evt);
            }
        });

        jAdmiPro.setText("Administración");
        jAdmiPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAdmiProActionPerformed(evt);
            }
        });
        jProducto.add(jAdmiPro);

        jConsProdu.setText("Consultas");
        jConsProdu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsProduActionPerformed(evt);
            }
        });
        jProducto.add(jConsProdu);

        jMenuBar1.add(jProducto);

        jClientes.setText("Clientes");

        jAdmiClien.setText("Administración ");
        jAdmiClien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAdmiClienActionPerformed(evt);
            }
        });
        jClientes.add(jAdmiClien);

        jConsClien.setText("Consultas");
        jConsClien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsClienActionPerformed(evt);
            }
        });
        jClientes.add(jConsClien);

        jMenuBar1.add(jClientes);

        jVentas.setText("Ventas");

        jAdmiVen.setText("Administración");
        jAdmiVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAdmiVenActionPerformed(evt);
            }
        });
        jVentas.add(jAdmiVen);

        jConsVen.setText("Consultas");
        jVentas.add(jConsVen);

        jMenuBar1.add(jVentas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAdmiProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdmiProActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ProductoAdm producto = new ProductoAdm();
        producto.setVisible(true);
        escritorio.add(producto);
        escritorio.moveToFront(producto);
    }//GEN-LAST:event_jAdmiProActionPerformed

    private void jAdmiClienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdmiClienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAdmiClienActionPerformed

    private void jConsClienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsClienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jConsClienActionPerformed

    private void jProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProductoActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jProductoActionPerformed

    private void jConsProduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsProduActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jConsProduActionPerformed

    private void jAdmiVenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdmiVenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAdmiVenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem jAdmiClien;
    private javax.swing.JMenuItem jAdmiPro;
    private javax.swing.JMenuItem jAdmiVen;
    private javax.swing.JMenu jClientes;
    private javax.swing.JMenuItem jConsClien;
    private javax.swing.JMenuItem jConsProdu;
    private javax.swing.JMenuItem jConsVen;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jProducto;
    private javax.swing.JMenu jVentas;
    // End of variables declaration//GEN-END:variables
}
