/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoventasg23.Vistas;

import java.awt.Color;
import javax.swing.JOptionPane;
import proyectoventasg23.AccesoADatos.ProductoData;
import proyectoventasg23.Entidades.Producto;

/**
 *
 * @author Altamirano
 */
public class ModificarProducto extends javax.swing.JInternalFrame {
private ProductoData proData = new ProductoData();
private Producto nuevoPro = new Producto();
    /**
     * Creates new form ModificarProducto
     */
    public ModificarProducto() {
        initComponents();
        limpiarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpEscritorio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jlPre = new javax.swing.JLabel();
        jlSto = new javax.swing.JLabel();
        jtNom = new javax.swing.JTextField();
        jtDes = new javax.swing.JTextField();
        jtPre = new javax.swing.JTextField();
        jtSto = new javax.swing.JTextField();
        jbMod = new javax.swing.JButton();
        jbBus = new javax.swing.JButton();
        jbNue = new javax.swing.JButton();
        jrEst = new javax.swing.JRadioButton();
        jlEst = new javax.swing.JLabel();
        jbEli = new javax.swing.JButton();
        jlnom = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jpEscritorio.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Modificar producto");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Ingrese el ID del producto: ");

        jtId.setText(" ");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Descripción:");

        jlPre.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jlPre.setText("Precio:");

        jlSto.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jlSto.setText("Stock:");

        jtNom.setText(" ");

        jtDes.setText("  ");

        jtPre.setText("  ");

        jbMod.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jbMod.setText("Modificar");
        jbMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModActionPerformed(evt);
            }
        });

        jbBus.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jbBus.setText("Buscar");
        jbBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBusActionPerformed(evt);
            }
        });

        jbNue.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jbNue.setText("Nuevo");
        jbNue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNueActionPerformed(evt);
            }
        });

        jrEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrEstActionPerformed(evt);
            }
        });

        jlEst.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jlEst.setText("Estado:");

        jbEli.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jbEli.setText("Eliminar");
        jbEli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliActionPerformed(evt);
            }
        });

        jlnom.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jlnom.setText("Nombre:");

        javax.swing.GroupLayout jpEscritorioLayout = new javax.swing.GroupLayout(jpEscritorio);
        jpEscritorio.setLayout(jpEscritorioLayout);
        jpEscritorioLayout.setHorizontalGroup(
            jpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEscritorioLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEscritorioLayout.createSequentialGroup()
                        .addGroup(jpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpEscritorioLayout.createSequentialGroup()
                                .addGroup(jpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlPre)
                                    .addComponent(jlnom))
                                .addGap(82, 82, 82)
                                .addGroup(jpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtNom)
                                    .addComponent(jtPre)))
                            .addGroup(jpEscritorioLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(60, 60, 60)
                                .addComponent(jtDes))
                            .addGroup(jpEscritorioLayout.createSequentialGroup()
                                .addComponent(jlEst)
                                .addGap(92, 92, 92)
                                .addGroup(jpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrEst)
                                    .addGroup(jpEscritorioLayout.createSequentialGroup()
                                        .addComponent(jbNue)
                                        .addGap(52, 52, 52)
                                        .addComponent(jbMod)
                                        .addGap(53, 53, 53)
                                        .addComponent(jbEli))
                                    .addComponent(jtSto, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpEscritorioLayout.createSequentialGroup()
                        .addGroup(jpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpEscritorioLayout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(jLabel1))
                            .addGroup(jpEscritorioLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbBus))
                            .addComponent(jlSto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jpEscritorioLayout.setVerticalGroup(
            jpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEscritorioLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBus))
                .addGap(18, 18, 18)
                .addGroup(jpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEscritorioLayout.createSequentialGroup()
                        .addComponent(jlnom)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEscritorioLayout.createSequentialGroup()
                        .addComponent(jtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlPre)
                    .addComponent(jtPre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEscritorioLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jlSto))
                    .addGroup(jpEscritorioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtSto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEscritorioLayout.createSequentialGroup()
                        .addComponent(jlEst)
                        .addGap(29, 29, 29)
                        .addGroup(jpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbNue)
                            .addComponent(jbMod)
                            .addComponent(jbEli)))
                    .addComponent(jrEst))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModActionPerformed
        // TODO add your handling code here:
        try {
          Integer idProducto = Integer.parseInt(jtId.getText());  
          String nom = jtNom.getText();
          String des = jtDes.getText();
          Double pre = Double.parseDouble(jtPre.getText());
          Integer sto = Integer.parseInt(jtSto.getText());
          if (nom.isEmpty()|| des.isEmpty()|| pre.equals(0)|| sto.equals(0)){
            JOptionPane.showMessageDialog(this, "no debe haber campos vacios");  
          }
          Boolean est = jrEst.isSelected();
          
          nuevoPro.setIdProducto(idProducto);
          nuevoPro.setNombreProducto(nom);
          nuevoPro.setDescripcion(des);
          nuevoPro.setPrecioActual(pre);
          nuevoPro.setStock(sto);
          proData.modificarProducto(nuevoPro); 
          
        } catch (NumberFormatException nfe){
             JOptionPane.showMessageDialog(this, "el id no es valido");
        }
        
    }//GEN-LAST:event_jbModActionPerformed

    private void jbBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBusActionPerformed
        // TODO add your handling code here:
        try{
            System.out.println("el número es: " +Integer.parseInt(jtId.getText()));
            int idProducto = Integer.parseInt(jtId.getText());
            nuevoPro = proData.buscarProducto(idProducto);
            nuevoPro.setEstado(true);
            if (nuevoPro!=null){
                
             jtNom.setText(nuevoPro.getNombreProducto());
             jtDes.setText(nuevoPro.getDescripcion());    
             jtPre.setText(nuevoPro.getPrecioActual()+ "");
             jtSto.setText(nuevoPro.getStock()+ "");
             jrEst.setSelected(nuevoPro.isEstado());
             
            }
            
       } catch(NumberFormatException ex){
           JOptionPane.showMessageDialog(this, "el id no es valido: " + ex);
           
       }
    }//GEN-LAST:event_jbBusActionPerformed

    private void jbNueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNueActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
        nuevoPro= null;
        
    }//GEN-LAST:event_jbNueActionPerformed

    private void jbEliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliActionPerformed
        // TODO add your handling code here:
          if (nuevoPro!=null){
            proData.eliminarProducto(nuevoPro.getIdProducto());
            nuevoPro = null;
            limpiarCampos();
        } else {
          JOptionPane.showMessageDialog(this, "no hay producto seleccionado");  
        }
    }//GEN-LAST:event_jbEliActionPerformed

    private void jrEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrEstActionPerformed
        // TODO add your handling code here:
        nuevoPro.isEstado();
       
    }//GEN-LAST:event_jrEstActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        dispose();
      /*  
        Productos vistaProductos = new Productos();
        vistaProductos.setVisible(true);
        jpEscritorio.add(vistaProductos);
        jpEscritorio.revalidate();
        vistaProductos.moveToFront();
         jpEscritorio.removeAll();
        jpEscritorio.repaint();
        */
        Productos vistaProducto = new Productos();
        vistaProducto.setVisible(true);
        vistaProducto.moveToFront();
        vistaProducto.getContentPane().setBackground(new Color(255, 153, 153));
        jpEscritorio.add(vistaProducto);
    }//GEN-LAST:event_formMouseClicked
    private void limpiarCampos(){
        jtId.setText("");
        jtNom.setText("");
        jtDes.setText("");
        jtPre.setText("");
        jtSto.setText("");
        jrEst.setSelected(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbBus;
    private javax.swing.JButton jbEli;
    private javax.swing.JButton jbMod;
    private javax.swing.JButton jbNue;
    private javax.swing.JLabel jlEst;
    private javax.swing.JLabel jlPre;
    private javax.swing.JLabel jlSto;
    private javax.swing.JLabel jlnom;
    private javax.swing.JPanel jpEscritorio;
    private javax.swing.JRadioButton jrEst;
    private javax.swing.JTextField jtDes;
    private javax.swing.JTextField jtId;
    private javax.swing.JTextField jtNom;
    private javax.swing.JTextField jtPre;
    private javax.swing.JTextField jtSto;
    // End of variables declaration//GEN-END:variables
}
