/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoventasg23.Vistas;

import java.sql.SQLException;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import proyectoventasg23.AccesoADatos.ProductoData;
import proyectoventasg23.Entidades.Producto;



public class Productos extends javax.swing.JInternalFrame {


private ProductoData proData = new ProductoData();
private Producto nuevoPro = null;
JInternalFrame vistaProducto = new JInternalFrame();   
    /**
     * Creates new form Producto
     */
    public Productos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jdEscritorio = new javax.swing.JDesktopPane();
        jNombre = new javax.swing.JLabel();
        jtNom = new javax.swing.JTextField();
        jDescripcion = new javax.swing.JLabel();
        jtDes = new javax.swing.JTextField();
        jPrecio = new javax.swing.JLabel();
        jtPre = new javax.swing.JTextField();
        jStock = new javax.swing.JLabel();
        jtSto = new javax.swing.JTextField();
        jbGuardar = new javax.swing.JButton();
        jbMod = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();

        jTextField3.setText("jTextField3");

        setBorder(null);
        setResizable(true);
        setTitle("Administración de Productos");
        setPreferredSize(new java.awt.Dimension(800, 600));

        jdEscritorio.setBackground(new java.awt.Color(255, 153, 153));

        jNombre.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jNombre.setText("Nombre");

        jDescripcion.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jDescripcion.setText("Descripción");

        jPrecio.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jPrecio.setText("Precio");

        jStock.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jStock.setText("Stock");

        jbGuardar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbMod.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jbMod.setText("Modificar");
        jbMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModActionPerformed(evt);
            }
        });

        jbSalir.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jdEscritorio.setLayer(jNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdEscritorio.setLayer(jtNom, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdEscritorio.setLayer(jDescripcion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdEscritorio.setLayer(jtDes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdEscritorio.setLayer(jPrecio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdEscritorio.setLayer(jtPre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdEscritorio.setLayer(jStock, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdEscritorio.setLayer(jtSto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdEscritorio.setLayer(jbGuardar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdEscritorio.setLayer(jbMod, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdEscritorio.setLayer(jbSalir, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdEscritorioLayout = new javax.swing.GroupLayout(jdEscritorio);
        jdEscritorio.setLayout(jdEscritorioLayout);
        jdEscritorioLayout.setHorizontalGroup(
            jdEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdEscritorioLayout.createSequentialGroup()
                .addGroup(jdEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jdEscritorioLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jNombre)
                        .addGap(90, 90, 90)
                        .addComponent(jtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jdEscritorioLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jPrecio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtPre, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jdEscritorioLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jStock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtSto, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdEscritorioLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbGuardar)
                        .addGap(14, 14, 14)
                        .addComponent(jbMod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbSalir))
                    .addGroup(jdEscritorioLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jDescripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtDes, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(479, Short.MAX_VALUE))
        );
        jdEscritorioLayout.setVerticalGroup(
            jdEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdEscritorioLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jdEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdEscritorioLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jNombre))
                    .addComponent(jtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jdEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdEscritorioLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jDescripcion))
                    .addGroup(jdEscritorioLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jtDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jdEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdEscritorioLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jPrecio))
                    .addComponent(jtPre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jdEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdEscritorioLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jStock))
                    .addGroup(jdEscritorioLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jtSto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(jdEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbMod)
                    .addComponent(jbSalir)
                    .addComponent(jbGuardar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdEscritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        dispose();
        } 
         private void limpiarCampos(){
        jtNom.setText("");
        jtDes.setText("");
        jtPre.setText("");
        jtSto.setText("");
       
  
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // TODO add your handling code here:
           try {
        String nombre = jtNom.getText();
        String descripcion = jtDes.getText();
        Double precio = Double.parseDouble(jtPre.getText());
        Integer stock = Integer.parseInt(jtSto.getText());
        if(nombre.isEmpty()||descripcion.isEmpty()||precio.equals(0)|| stock.equals(0)){
            JOptionPane.showMessageDialog(this,"no puede haber campos vacios");
      }
        if (nuevoPro == null){
                nuevoPro = new Producto (nombre, descripcion, precio, stock, true);
                proData.guardarProducto(nuevoPro);
                
           }
      
      }catch (NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, "no se pudo ingresar a la tabla"); 
     }
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModActionPerformed
        // TODO add your handling code here:
        ModificarProducto vistaModPro = new ModificarProducto();
       // jdEscritorio.removeAll();
        jdEscritorio.add(vistaModPro);
        jdEscritorio.revalidate();
        vistaModPro.setVisible(true);
        vistaModPro.moveToFront();
    }//GEN-LAST:event_jbModActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jDescripcion;
    private javax.swing.JLabel jNombre;
    private javax.swing.JLabel jPrecio;
    private javax.swing.JLabel jStock;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbMod;
    private javax.swing.JButton jbSalir;
    private javax.swing.JDesktopPane jdEscritorio;
    private javax.swing.JTextField jtDes;
    private javax.swing.JTextField jtNom;
    private javax.swing.JTextField jtPre;
    private javax.swing.JTextField jtSto;
    // End of variables declaration//GEN-END:variables
}
